# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-05-25 01:14-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:107
msgid "failed to load pilot"
msgstr "misslyckades med att ladda pilot"

#: pypilot/autopilot.py:110
msgid "Available Pilots"
msgstr "Tillgängliga piloter"

#: pypilot/autopilot.py:136
msgid "warning: failed to open special file"
msgstr "varning: det gick inte att öppna specialfilen"

#: pypilot/autopilot.py:136
msgid "for writing"
msgstr "för skrivande"

#: pypilot/autopilot.py:137
msgid "cannot stroke the watchdog"
msgstr "kan inte stryka vakthunden"

#: pypilot/autopilot.py:141
msgid "warning: failed to make autopilot process realtime"
msgstr "varning: misslyckades med att göra autopilotprocessen i realtid"

#: pypilot/autopilot.py:309
msgid "server/client is running too _slowly_"
msgstr "servern / klienten körs för _slowly_"

#: pypilot/autopilot.py:315
msgid "sensors is running too _slowly_"
msgstr "sensorerna går för långsamt"

#: pypilot/autopilot.py:365
msgid "autopilot routine is running too _slowly_"
msgstr "autopilotrutinen går för långsamt"

#: pypilot/autopilot.py:370
msgid "servo is running too _slowly_"
msgstr "servo går för långsamt"

#: pypilot/boatimu.py:34
msgid "RTIMU library not detected, please install it"
msgstr "RTIMU-biblioteket upptäcktes inte. Installera det"

#: pypilot/boatimu.py:57
msgid "Using settings file"
msgstr "Använda inställningsfilen"

#: pypilot/boatimu.py:97
msgid "ERROR: No IMU Detected"
msgstr "FEL: Ingen IMU upptäckt"

#: pypilot/boatimu.py:105
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "FEL: IMU Init misslyckades, inga tröghetsdata tillgängliga"

#: pypilot/boatimu.py:127
msgid "warning, failed to make imu process realtime"
msgstr "varning, kunde inte göra imu-processen i realtid"

#: pypilot/boatimu.py:129
msgid "made imu process realtime"
msgstr "gjorde imu-processen i realtid"

#: pypilot/boatimu.py:141
msgid "setting initial gyro bias"
msgstr "ställa in initial gyro bias"

#: pypilot/boatimu.py:157
msgid "imu process failed to keep time"
msgstr "imu-processen kunde inte hålla tiden"

#: pypilot/boatimu.py:165
msgid "failed to read IMU!"
msgstr "misslyckades med att läsa IMU!"

#: pypilot/boatimu.py:197
msgid "imu rate set to rate"
msgstr "imu-hastighet inställd på rate"

#: pypilot/boatimu.py:211
msgid "too high standing gyro bias, resetting sensors"
msgstr "för hög stående gyroförspänning, återställning av sensorer"

#: pypilot/boatimu.py:216
msgid "compass out of range, resetting"
msgstr "kompass utanför räckvidden, återställs"

#: pypilot/boatimu.py:308
msgid "warning, failed to make calibration process other"
msgstr "varning, misslyckades med att göra kalibreringsprocessen annan"

#: pypilot/boatimu.py:310
msgid "warning, failed to make calibration process idle, trying renice"
msgstr "varning, misslyckades med att göra kalibreringsprocessen inaktiv"

#: pypilot/boatimu.py:312
msgid "warning, failed to renice calibration process"
msgstr "varning, misslyckades med att avbryta kalibreringsprocessen"

#: pypilot/boatimu.py:320
msgid "calibration loaded, starting"
msgstr "kalibrering laddad, startar"

#: pypilot/boatimu.py:323
msgid "failed import calibration fit"
msgstr "misslyckad importkalibrering"

#: pypilot/boatimu.py:339
msgid "terminate calibration process"
msgstr "avsluta kalibreringsprocessen"

#: pypilot/boatimu.py:429
msgid "accel values invalid"
msgstr "accelvärden är ogiltiga"

#: pypilot/bufferedsocket.py:56
msgid "overflow in pypilot udp socket"
msgstr "överflöd i pypilot udp-uttag"

#: pypilot/bufferedsocket.py:61
msgid "overflow in pypilot socket"
msgstr "överflöd i pypilotuttag"

#: pypilot/bufferedsocket.py:71
msgid "failed to send udp packet"
msgstr "misslyckades med att skicka udp-paket"

#: pypilot/bufferedsocket.py:80
msgid "pypilot socket failed to send to"
msgstr "pypilotuttaget kunde inte skickas till"

#: pypilot/bufferedsocket.py:93
msgid "socket send took too long!?!?"
msgstr "sändningsuttag tog för lång tid!?!?"

#: pypilot/bufferedsocket.py:95
msgid "socket send error"
msgstr "sändningsfel"

#: pypilot/bufferedsocket.py:99
msgid "pypilot socket exception"
msgstr "undantag för pypilotuttag"

#: pypilot/bufferedsocket.py:103
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr ""
"faller tillbaka till Python nonblocking-uttag, kommer att konsumera mer CPU"

#: pypilot/bufferedsocket.py:129
msgid "socket send error in server flush"
msgstr "socket skicka fel i server spolning"

#: pypilot/bufferedsocket.py:144
msgid "error receiving data"
msgstr "fel vid mottagande av data"

#: pypilot/calibration_fit.py:39
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"misslyckades med att ladda vetenskapligt bibliotek, kan inte utföra "
"kalibreringsuppdatering!"

#: pypilot/client.py:97
msgid "warning, registering existing value:"
msgstr "varning, registrera befintligt värde:"

#: pypilot/client.py:155
msgid "failed to read config file:"
msgstr "misslyckades med att läsa konfigurationsfil:"

#: pypilot/client.py:186
msgid "failed to write config file:"
msgstr "misslyckades med att skriva konfigurationsfil:"

#: pypilot/client.py:188
msgid "Exception writing config file:"
msgstr "Konfigurationsfil för undantagsskrivning:"

#: pypilot/client.py:265
msgid "invalid message from server:"
msgstr "ogiltigt meddelande från servern:"

#: pypilot/client.py:281
msgid "warning, pypilot client aleady has connection"
msgstr "varning, pypilotklienten har redan anslutning"

#: pypilot/client.py:301
msgid "connect failed to"
msgstr "anslutning misslyckades med"

#: pypilot/client.py:388
msgid "failed to connect to"
msgstr "misslyckades med att ansluta till"

#: pypilot/client.py:445
msgid "usage"
msgstr "användande"

#: pypilot/client.py:448
msgid "set the host or ip address"
msgstr "ställa in värden eller ip-adressen"

#: pypilot/client.py:449
msgid "print info about each value type"
msgstr "skriva ut information om varje värdetyp"

#: pypilot/client.py:450
msgid "continuous watch"
msgstr "kontinuerlig klocka"

#: pypilot/client.py:451
msgid "show this message"
msgstr "visa detta meddelande"

#: pypilot/client.py:478
msgid "failed to retrieve value list!"
msgstr "misslyckades med att hämta värdelistan!"

#: pypilot/client.py:489
msgid "timeout retrieving"
msgstr "timeout hämtning"

#: pypilot/client.py:492
msgid "missing"
msgstr "saknas"

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot kunde inte importera nödvändiga moduler. Glömde du att köra sudo "
"python3 setup.py install?"

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr "GPSD ansluten"

#: pypilot/gpsd.py:48
msgid "gpsd failed to connect"
msgstr "gpsd kunde inte ansluta"

#: pypilot/gpsd.py:53
msgid "exception connecting to gps"
msgstr "undantag som ansluter till GPS"

#: pypilot/gpsd.py:57
msgid "gpsd disconnected"
msgstr "gpsd frånkopplad"

#: pypilot/gpsd.py:71
msgid "gpsd PROBE success"
msgstr "gpsd PROBE framgång"

#: pypilot/gpsd.py:79
msgid "gpsd probe failed"
msgstr "gpsd-sonden misslyckades"

#: pypilot/gpsd.py:102
msgid "gpsd deactivated"
msgstr "GPSD inaktiverad"

#: pypilot/gpsd.py:135
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd misslyckades med att bestämma enhetens överföringshastighet"

#: pypilot/gpsd.py:152
msgid "gpsd timeout from lack of data"
msgstr "gpsd-timeout från brist på data"

#: pypilot/gpsd.py:167
msgid "gpsd received invalid message"
msgstr "gpsd fick ogiltigt meddelande"

#: pypilot/gpsd.py:212
msgid "gpsd got flag for pipe:"
msgstr "gpsd fick flagga för rör:"

#: pypilot/gpsd.py:221
msgid "gpsd serial probe"
msgstr "gpsd seriell sond"

#: pypilot/nmea.py:87
msgid "nmea failed to parse gps"
msgstr "nmea misslyckades med att analysera GPS"

#: pypilot/nmea.py:127
msgid "nmea failed to parse wind"
msgstr "nmea misslyckades med att analysera vind"

#: pypilot/nmea.py:189
msgid "exception parsing apb"
msgstr "undantagsparsning apb"

#: pypilot/nmea.py:277
msgid "unhandled nmea pipe string"
msgstr "obehandlad nmea-rörsträng"

#: pypilot/nmea.py:327
msgid "lost serial"
msgstr "förlorad serie"

#: pypilot/nmea.py:350
msgid "nmea got flag for process pipe:"
msgstr "nmea fick flagga för processrör:"

#: pypilot/nmea.py:371
msgid "is another process accessing it?"
msgstr "har en annan process tillgång till den?"

#: pypilot/nmea.py:373
msgid "serial device timed out"
msgstr "tidsenhet för seriell enhet"

#: pypilot/nmea.py:429
msgid "failed to open"
msgstr "gick inte att öppna"

#: pypilot/nmea.py:482
msgid "nmea server on port"
msgstr "nmea-server på port"

#: pypilot/nmea.py:482
msgid "bind failed."
msgstr "bindningen misslyckades."

#: pypilot/nmea.py:484
msgid "listening on port"
msgstr "lyssnar på port"

#: pypilot/nmea.py:484
msgid "for nmea connections"
msgstr "för nmea-anslutningar"

#: pypilot/nmea.py:550
msgid "nmea server has too many connections"
msgstr "nmea-servern har för många anslutningar"

#: pypilot/nmea.py:576
msgid "nmea sock not in sockets!"
msgstr "nmea strumpa inte i uttag!"

#: pypilot/nmea.py:587
msgid "nmea failed to unregister socket"
msgstr "nmea kunde inte avregistrera sockeln"

#: pypilot/nmea.py:592
msgid "nmea failed to remove fd"
msgstr "nmea misslyckades med att ta bort fd"

#: pypilot/nmea.py:597
msgid "nmea failed to remove address"
msgstr "nmea kunde inte ta bort adressen"

#: pypilot/nmea.py:610
msgid "connected to"
msgstr "anslutet till"

#: pypilot/nmea.py:610
msgid "in"
msgstr "i"

#: pypilot/nmea.py:610
msgid "seconds"
msgstr "sekunder"

#: pypilot/nmea.py:614
msgid "nmea client failed to connect to"
msgstr "nmea-klienten kunde inte ansluta till"

#: pypilot/nmea.py:641
msgid "poll took too long in nmea process!"
msgstr "enkäten tog för lång tid i nmea-processen!"

#: pypilot/nmea.py:648
msgid "nmea bridge lost server connection"
msgstr "nmea bridge förlorad serveranslutning"

#: pypilot/nmea.py:651
msgid "nmea bridge lost pipe to autopilot"
msgstr "nmea bridge förlorade röret till autopiloten"

#: pypilot/nmea.py:670
msgid "nmea bridge unhandled poll flag"
msgstr "nmea bridge obehandlad omröstningsflagga"

#: pypilot/nmea.py:707
msgid "failed to create nmea socket as host:port"
msgstr "misslyckades med att skapa nmea-uttag som värd: port"

#: pypilot/nmea.py:713
msgid "nmea process loop too slow:"
msgstr "nmea processlinga för långsam:"

#: pypilot/nonblockingpipe.py:41
msgid "error pipe block on recv!"
msgstr "fel rör block på recv!"

#: pypilot/nonblockingpipe.py:43
msgid "failed to recv nonblocking pipe!"
msgstr "misslyckades med att recv non-blocking pipe!"

#: pypilot/nonblockingpipe.py:70
msgid "pipe full"
msgstr "röret fullt"

#: pypilot/nonblockingpipe.py:70
msgid "cannot send"
msgstr "kan inte skicka"

#: pypilot/nonblockingpipe.py:90 pypilot/nonblockingpipe.py:146
msgid "failed to decode data socket!"
msgstr "misslyckades med att avkoda datauttaget!"

#: pypilot/nonblockingpipe.py:104
msgid "failed to encode data socket!"
msgstr "misslyckades med att koda datauttaget!"

#: pypilot/nonblockingpipe.py:156
msgid "failed write"
msgstr "misslyckades skriva"

#: pypilot/pyjson.py:15
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"VARNING: Python ujson-biblioteket misslyckades, parsing kommer att konsumera"
" mer CPU"

#: pypilot/rudder.py:118
msgid "bad rudder calibration"
msgstr "dålig roderkalibrering"

#: pypilot/rudder.py:122
msgid "bad servo rudder calibration"
msgstr "dålig servoroder kalibrering"

#: pypilot/rudder.py:194
msgid "servo rudder autogain failed"
msgstr "Servo roder autogain misslyckades"

#: pypilot/sensors.py:43
msgid "sensor found"
msgstr "sensor hittades"

#: pypilot/sensors.py:192
msgid "unknown data parsed!"
msgstr "okända data analyserade!"

#: pypilot/serialprobe.py:31
msgid "error reading"
msgstr "felläsning"

#: pypilot/serialprobe.py:87
msgid "found more devices by path"
msgstr "hittade fler enheter efter sökväg"

#: pypilot/serialprobe.py:119
msgid "removing gps device"
msgstr "tar bort GPS-enhet"

#: pypilot/serialprobe.py:195
msgid "no pyudev module! will scan usb devices often!"
msgstr "ingen pyudev-modul! kommer att skanna USB-enheter ofta!"

#: pypilot/serialprobe.py:357
msgid "success"
msgstr "Framgång"

#: pypilot/serialprobe.py:365
msgid "failed to record device"
msgstr "det gick inte att spela in enheten"

#: pypilot/server.py:97
msgid "ERROR no connections in watch"
msgstr "FEL inga anslutningar i klockan"

#: pypilot/server.py:200
msgid "remove duplicate udp connection"
msgstr "ta bort dubbletter av utp-anslutning"

#: pypilot/server.py:340 ui/boatplot.py:110
msgid "failed to load"
msgstr "misslyckades att ladda"

#: pypilot/server.py:351
msgid "backup data failed as well"
msgstr "säkerhetskopieringsdata misslyckades också"

#: pypilot/server.py:379
msgid "failed to write"
msgstr "misslyckades med att skriva"

#: pypilot/server.py:436
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: bindning misslyckades; kör du redan en server?"

#: pypilot/server.py:498
msgid "persistent store took too long!"
msgstr "ihållande butik tog för lång tid!"

#: pypilot/server.py:514
msgid "max connections reached"
msgstr "max anslutningar uppnåtts"

#: pypilot/server.py:517
msgid "server add socket"
msgstr "server lägga till uttag"

#: pypilot/server.py:527
msgid "internal pipe closed, server exiting"
msgstr "internt rör stängt, server avslutas"

#: pypilot/server.py:579
msgid "server socket closed from flush!!"
msgstr "serveruttag stängt från spolning !!"

#: pypilot/servo.py:449
msgid "servo calibration invalid"
msgstr "servokalibrering ogiltig"

#: pypilot/servo.py:557
msgid "failed to open servo on:"
msgstr "misslyckades med att öppna servo på:"

#: pypilot/servo.py:564
msgid "failed set nonblocking/exclusive"
msgstr "misslyckades ställa in blockering / exklusiv"

#: pypilot/servo.py:595
msgid "found"
msgstr "hittades"

#: pypilot/servo.py:716
msgid "loading servo calibration"
msgstr "laddning av servokalibrering"

#: pypilot/servo.py:720
msgid "WARNING: using default servo calibration!!"
msgstr "VARNING: använder standard servokalibrering !!"

#: pypilot/servo.py:729
msgid "probing"
msgstr "sondering"

#: pypilot/servo.py:745
msgid "arduino servo detected"
msgstr "arduino servo upptäckt"

#: pypilot/servo.py:754
msgid "device needed for option"
msgstr "enhet som behövs för alternativet"

#: pypilot/signalk.py:67
msgid "read token"
msgstr "läs token"

#: pypilot/signalk.py:70
msgid "failed to read token"
msgstr "misslyckades med att läsa token"

#: pypilot/signalk.py:77
msgid "failed to"
msgstr "misslyckades att"

#: pypilot/signalk.py:77
msgid "autodetection not possible"
msgstr "autodetektion inte möjlig"

#: pypilot/signalk.py:78 pypilot/signalk.py:144 pypilot/signalk.py:213
msgid "try"
msgstr "Prova"

#: pypilot/signalk.py:78 pypilot/signalk.py:144 pypilot/signalk.py:213
msgid "or"
msgstr "eller"

#: pypilot/signalk.py:109
msgid "service removed"
msgstr "tjänsten borttagen"

#: pypilot/signalk.py:113
msgid "signalk server lost"
msgstr "signalk-server förlorad"

#: pypilot/signalk.py:116
msgid "service add"
msgstr "tjänsten lägg till"

#: pypilot/signalk.py:130
msgid "server found"
msgstr "server hittades"

#: pypilot/signalk.py:139
msgid "probe"
msgstr "sond"

#: pypilot/signalk.py:143
msgid "could not"
msgstr "kunde inte"

#: pypilot/signalk.py:153
msgid "failed to retrieve/parse data from"
msgstr "misslyckades med att hämta / analysera data från"

#: pypilot/signalk.py:156
msgid "signalk found"
msgstr "signalk hittades"

#: pypilot/signalk.py:168
msgid "see if token is ready"
msgstr "se om token är redo"

#: pypilot/signalk.py:174
msgid "received token"
msgstr "mottog token"

#: pypilot/signalk.py:180
msgid "failed to store token"
msgstr "misslyckades med att lagra token"

#: pypilot/signalk.py:184
msgid "error requesting access"
msgstr "fel vid begäran om åtkomst"

#: pypilot/signalk.py:203
msgid "signalk request access url"
msgstr "webbadress för signalk begäran om åtkomst"

#: pypilot/signalk.py:205
msgid "signalk error requesting access"
msgstr "signalk-fel som begär åtkomst"

#: pypilot/signalk.py:212
msgid "cannot create connection:"
msgstr "kan inte skapa anslutning:"

#: pypilot/signalk.py:226
msgid "failed to connect"
msgstr "misslyckades med att ansluta"

#: pypilot/signalk.py:270
msgid "signalk connected to"
msgstr "skylt kopplad till"

#: pypilot/signalk.py:313
msgid "signalk failed to parse"
msgstr "signalk misslyckades med att analysera"

#: pypilot/signalk.py:331
msgid "Exception converting signalk->pypilot"
msgstr "Undantag konverterar signalk-> pypilot"

#: pypilot/signalk.py:345
msgid "received"
msgstr "mottagen"

#: pypilot/signalk.py:391
msgid "signalk failed to send"
msgstr "signalk kunde inte skickas"

#: pypilot/signalk.py:404
msgid "signalk failed to parse msg:"
msgstr "signalk misslyckades med att analysera msg:"

#: pypilot/values.py:131
msgid "invalid initial value for range property"
msgstr "ogiltigt initialvärde för intervallegenskap"

#: pypilot/values.py:180
msgid "invalid set"
msgstr "ogiltig uppsättning"

#: pypilot/pilots/__init__.py:25
msgid "ERROR loading"
msgstr "Problem med att ladda"

#: ui/autopilot_calibration.py:167
msgid "exception in calibration:"
msgstr "undantag vid kalibrering:"

#: ui/autopilot_control.py:265
msgid "warning: unhandled message"
msgstr "varning: okontrollerat meddelande"

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr "Autopilotkontroll"

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr "Du"

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:455 ui/autopilot_control_ui.py:732
msgid "N/A"
msgstr "Ej tillämpligt"

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr "Ej tillämpligt"

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr "----"

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr "Ej tillämpligt"

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr "hamn"

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr "styrbord"

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr "Pilot"

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:420
msgid "Compass"
msgstr "Kompass"

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr "GPS"

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr "Vind"

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr "True Wind"

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr "Centrum"

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr "&Omfattning"

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr "&Klient"

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr "C&alibrering"

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr "Stänga"

#: ui/autopilot_control_ui.py:299 ui/autopilot_control_ui.py:529
#: ui/autopilot_control_ui.py:649
msgid "Calibration"
msgstr "Kalibrering"

#: ui/autopilot_control_ui.py:349
msgid "Boat is level"
msgstr "Båten är jämn"

#: ui/autopilot_control_ui.py:356 ui/client_wx.py:159 ui/scope_ui.py:94
msgid "Reset"
msgstr "Återställa"

#: ui/autopilot_control_ui.py:377
msgid "Alignment"
msgstr "Inriktning"

#: ui/autopilot_control_ui.py:394
msgid "Heading"
msgstr "Rubrik"

#: ui/autopilot_control_ui.py:399 ui/autopilot_control_ui.py:465
#: ui/autopilot_control_ui.py:475
msgid "     N/A     "
msgstr "Ej tillämpligt"

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:755
msgid "Offset"
msgstr "Offset"

#: ui/autopilot_control_ui.py:418
msgid "Coords"
msgstr "Koordiner"

#: ui/autopilot_control_ui.py:420
msgid "Sea"
msgstr "Hav"

#: ui/autopilot_control_ui.py:420
msgid "Boat"
msgstr "Båt"

#: ui/autopilot_control_ui.py:443 ui/client_wx.py:52
msgid "Scope"
msgstr "Omfattning"

#: ui/autopilot_control_ui.py:450
msgid "Pitch"
msgstr "Tonhöjd"

#: ui/autopilot_control_ui.py:460
msgid "Roll"
msgstr "Rulla"

#: ui/autopilot_control_ui.py:470
msgid "Heel"
msgstr "Häl"

#: ui/autopilot_control_ui.py:497
msgid "alignment"
msgstr "inriktning"

#: ui/autopilot_control_ui.py:539 ui/autopilot_control_ui.py:659
msgid "Calibration Age"
msgstr "Kalibreringsålder"

#: ui/autopilot_control_ui.py:556 ui/autopilot_control_ui.py:676
msgid "Clear"
msgstr "Klar"

#: ui/autopilot_control_ui.py:559 ui/autopilot_control_ui.py:679
msgid "calibration locked"
msgstr "kalibrering låst"

#: ui/autopilot_control_ui.py:582
msgid "accel"
msgstr "accelera"

#: ui/autopilot_control_ui.py:613
msgid "Sigma Points"
msgstr "Sigma-poäng"

#: ui/autopilot_control_ui.py:620
msgid "local history"
msgstr "lokalhistoria"

#: ui/autopilot_control_ui.py:627
msgid "current"
msgstr "nuvarande"

#: ui/autopilot_control_ui.py:634
msgid "Calibration Points"
msgstr "Kalibreringspunkter"

#: ui/autopilot_control_ui.py:703
msgid "compass"
msgstr "kompass"

#: ui/autopilot_control_ui.py:713
msgid ""
"Press each button when the rudder is at the correct position to calibrate."
msgstr "Tryck på varje knapp när rodret är i rätt läge för att kalibrera."

#: ui/autopilot_control_ui.py:727
msgid "Rudder"
msgstr "Roder"

#: ui/autopilot_control_ui.py:742
msgid "Reset Calibration"
msgstr "Återställ kalibrering"

#: ui/autopilot_control_ui.py:752
msgid "Rudder Is Centered"
msgstr "Roder är centrerad"

#: ui/autopilot_control_ui.py:760 ui/autopilot_control_ui.py:773
#: ui/autopilot_control_ui.py:786
msgid "------"
msgstr "------"

#: ui/autopilot_control_ui.py:765
msgid "Rudder is Starboard Range"
msgstr "Roder är styrbordsområde"

#: ui/autopilot_control_ui.py:768
msgid "Scale"
msgstr "Skala"

#: ui/autopilot_control_ui.py:778
msgid "Rudder is Port Range"
msgstr "Ror är hamnområde"

#: ui/autopilot_control_ui.py:781
msgid "Non Linearity"
msgstr "Icke linjäritet"

#: ui/autopilot_control_ui.py:798
msgid " range +-"
msgstr "intervall + -"

#: ui/autopilot_control_ui.py:806
msgid "degrees"
msgstr "grader"

#: ui/autopilot_control_ui.py:825
msgid "rudder"
msgstr "roder"

#: ui/autopilot_control_ui.py:827
msgid "settings"
msgstr "inställningar"

#: ui/boatplot.py:26
msgid "failed to load pywavefront:"
msgstr ""

#: ui/boatplot.py:56
msgid "invalid display dimensions"
msgstr ""

#: ui/boatplot.py:111
msgid "Did you add the pypilot_data repository?"
msgstr ""

#: ui/boatplot.py:161
msgid "not found, texture compass cannot be used"
msgstr ""

#: ui/client_wx.py:48
msgid "Refresh"
msgstr ""

#: ui/client_wx.py:190
msgid "Connected"
msgstr ""

#: ui/client_wx.py:192
msgid "Disconnected"
msgstr ""

#: ui/client_wx.py:219
msgid "warning, invalid choice value specified"
msgstr ""

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr ""

#: ui/scope_ui.py:73
msgid "Zero"
msgstr ""

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr ""

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr ""

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr ""

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr ""

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr ""

#: ui/scope_ui.py:97
msgid "fftw"
msgstr ""

#: ui/scope_ui.py:100
msgid "Time"
msgstr ""

#: ui/scope_wx.py:68
msgid "values not found:"
msgstr ""
