# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-05-25 01:14-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:107
msgid "failed to load pilot"
msgstr ""

#: pypilot/autopilot.py:110
msgid "Available Pilots"
msgstr ""

#: pypilot/autopilot.py:136
msgid "warning: failed to open special file"
msgstr ""

#: pypilot/autopilot.py:136
msgid "for writing"
msgstr ""

#: pypilot/autopilot.py:137
msgid "cannot stroke the watchdog"
msgstr ""

#: pypilot/autopilot.py:141
msgid "warning: failed to make autopilot process realtime"
msgstr ""

#: pypilot/autopilot.py:309
msgid "server/client is running too _slowly_"
msgstr ""

#: pypilot/autopilot.py:315
msgid "sensors is running too _slowly_"
msgstr ""

#: pypilot/autopilot.py:365
msgid "autopilot routine is running too _slowly_"
msgstr ""

#: pypilot/autopilot.py:370
msgid "servo is running too _slowly_"
msgstr ""

#: pypilot/boatimu.py:34
msgid "RTIMU library not detected, please install it"
msgstr ""

#: pypilot/boatimu.py:57
msgid "Using settings file"
msgstr ""

#: pypilot/boatimu.py:97
msgid "ERROR: No IMU Detected"
msgstr ""

#: pypilot/boatimu.py:105
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr ""

#: pypilot/boatimu.py:127
msgid "warning, failed to make imu process realtime"
msgstr ""

#: pypilot/boatimu.py:129
msgid "made imu process realtime"
msgstr ""

#: pypilot/boatimu.py:141
msgid "setting initial gyro bias"
msgstr ""

#: pypilot/boatimu.py:157
msgid "imu process failed to keep time"
msgstr ""

#: pypilot/boatimu.py:165
msgid "failed to read IMU!"
msgstr ""

#: pypilot/boatimu.py:197
msgid "imu rate set to rate"
msgstr ""

#: pypilot/boatimu.py:211
msgid "too high standing gyro bias, resetting sensors"
msgstr ""

#: pypilot/boatimu.py:216
msgid "compass out of range, resetting"
msgstr ""

#: pypilot/boatimu.py:308
msgid "warning, failed to make calibration process other"
msgstr ""

#: pypilot/boatimu.py:310
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""

#: pypilot/boatimu.py:312
msgid "warning, failed to renice calibration process"
msgstr ""

#: pypilot/boatimu.py:320
msgid "calibration loaded, starting"
msgstr ""

#: pypilot/boatimu.py:323
msgid "failed import calibration fit"
msgstr ""

#: pypilot/boatimu.py:339
msgid "terminate calibration process"
msgstr ""

#: pypilot/boatimu.py:429
msgid "accel values invalid"
msgstr ""

#: pypilot/bufferedsocket.py:56
msgid "overflow in pypilot udp socket"
msgstr ""

#: pypilot/bufferedsocket.py:61
msgid "overflow in pypilot socket"
msgstr ""

#: pypilot/bufferedsocket.py:71
msgid "failed to send udp packet"
msgstr ""

#: pypilot/bufferedsocket.py:80
msgid "pypilot socket failed to send to"
msgstr ""

#: pypilot/bufferedsocket.py:93
msgid "socket send took too long!?!?"
msgstr ""

#: pypilot/bufferedsocket.py:95
msgid "socket send error"
msgstr ""

#: pypilot/bufferedsocket.py:99
msgid "pypilot socket exception"
msgstr ""

#: pypilot/bufferedsocket.py:103
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr ""

#: pypilot/bufferedsocket.py:129
msgid "socket send error in server flush"
msgstr ""

#: pypilot/bufferedsocket.py:144
msgid "error receiving data"
msgstr ""

#: pypilot/calibration_fit.py:39
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""

#: pypilot/client.py:97
msgid "warning, registering existing value:"
msgstr ""

#: pypilot/client.py:155
msgid "failed to read config file:"
msgstr ""

#: pypilot/client.py:186
msgid "failed to write config file:"
msgstr ""

#: pypilot/client.py:188
msgid "Exception writing config file:"
msgstr ""

#: pypilot/client.py:265
msgid "invalid message from server:"
msgstr ""

#: pypilot/client.py:281
msgid "warning, pypilot client aleady has connection"
msgstr ""

#: pypilot/client.py:301
msgid "connect failed to"
msgstr ""

#: pypilot/client.py:388
msgid "failed to connect to"
msgstr ""

#: pypilot/client.py:445
msgid "usage"
msgstr ""

#: pypilot/client.py:448
msgid "set the host or ip address"
msgstr ""

#: pypilot/client.py:449
msgid "print info about each value type"
msgstr ""

#: pypilot/client.py:450
msgid "continuous watch"
msgstr ""

#: pypilot/client.py:451
msgid "show this message"
msgstr ""

#: pypilot/client.py:478
msgid "failed to retrieve value list!"
msgstr ""

#: pypilot/client.py:489
msgid "timeout retrieving"
msgstr ""

#: pypilot/client.py:492
msgid "missing"
msgstr ""

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr ""

#: pypilot/gpsd.py:48
msgid "gpsd failed to connect"
msgstr ""

#: pypilot/gpsd.py:53
msgid "exception connecting to gps"
msgstr ""

#: pypilot/gpsd.py:57
msgid "gpsd disconnected"
msgstr ""

#: pypilot/gpsd.py:71
msgid "gpsd PROBE success"
msgstr ""

#: pypilot/gpsd.py:79
msgid "gpsd probe failed"
msgstr ""

#: pypilot/gpsd.py:102
msgid "gpsd deactivated"
msgstr ""

#: pypilot/gpsd.py:135
msgid "gpsd failed to determine serial baud rate of device"
msgstr ""

#: pypilot/gpsd.py:152
msgid "gpsd timeout from lack of data"
msgstr ""

#: pypilot/gpsd.py:167
msgid "gpsd received invalid message"
msgstr ""

#: pypilot/gpsd.py:212
msgid "gpsd got flag for pipe:"
msgstr ""

#: pypilot/gpsd.py:221
msgid "gpsd serial probe"
msgstr ""

#: pypilot/nmea.py:87
msgid "nmea failed to parse gps"
msgstr ""

#: pypilot/nmea.py:127
msgid "nmea failed to parse wind"
msgstr ""

#: pypilot/nmea.py:189
msgid "exception parsing apb"
msgstr ""

#: pypilot/nmea.py:277
msgid "unhandled nmea pipe string"
msgstr ""

#: pypilot/nmea.py:327
msgid "lost serial"
msgstr ""

#: pypilot/nmea.py:350
msgid "nmea got flag for process pipe:"
msgstr ""

#: pypilot/nmea.py:371
msgid "is another process accessing it?"
msgstr ""

#: pypilot/nmea.py:373
msgid "serial device timed out"
msgstr ""

#: pypilot/nmea.py:429
msgid "failed to open"
msgstr ""

#: pypilot/nmea.py:482
msgid "nmea server on port"
msgstr ""

#: pypilot/nmea.py:482
msgid "bind failed."
msgstr ""

#: pypilot/nmea.py:484
msgid "listening on port"
msgstr ""

#: pypilot/nmea.py:484
msgid "for nmea connections"
msgstr ""

#: pypilot/nmea.py:550
msgid "nmea server has too many connections"
msgstr ""

#: pypilot/nmea.py:576
msgid "nmea sock not in sockets!"
msgstr ""

#: pypilot/nmea.py:587
msgid "nmea failed to unregister socket"
msgstr ""

#: pypilot/nmea.py:592
msgid "nmea failed to remove fd"
msgstr ""

#: pypilot/nmea.py:597
msgid "nmea failed to remove address"
msgstr ""

#: pypilot/nmea.py:610
msgid "connected to"
msgstr ""

#: pypilot/nmea.py:610
msgid "in"
msgstr ""

#: pypilot/nmea.py:610
msgid "seconds"
msgstr ""

#: pypilot/nmea.py:614
msgid "nmea client failed to connect to"
msgstr ""

#: pypilot/nmea.py:641
msgid "poll took too long in nmea process!"
msgstr ""

#: pypilot/nmea.py:648
msgid "nmea bridge lost server connection"
msgstr ""

#: pypilot/nmea.py:651
msgid "nmea bridge lost pipe to autopilot"
msgstr ""

#: pypilot/nmea.py:670
msgid "nmea bridge unhandled poll flag"
msgstr ""

#: pypilot/nmea.py:707
msgid "failed to create nmea socket as host:port"
msgstr ""

#: pypilot/nmea.py:713
msgid "nmea process loop too slow:"
msgstr ""

#: pypilot/nonblockingpipe.py:41
msgid "error pipe block on recv!"
msgstr ""

#: pypilot/nonblockingpipe.py:43
msgid "failed to recv nonblocking pipe!"
msgstr ""

#: pypilot/nonblockingpipe.py:70
msgid "pipe full"
msgstr ""

#: pypilot/nonblockingpipe.py:70
msgid "cannot send"
msgstr ""

#: pypilot/nonblockingpipe.py:90 pypilot/nonblockingpipe.py:146
msgid "failed to decode data socket!"
msgstr ""

#: pypilot/nonblockingpipe.py:104
msgid "failed to encode data socket!"
msgstr ""

#: pypilot/nonblockingpipe.py:156
msgid "failed write"
msgstr ""

#: pypilot/pyjson.py:15
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""

#: pypilot/rudder.py:118
msgid "bad rudder calibration"
msgstr ""

#: pypilot/rudder.py:122
msgid "bad servo rudder calibration"
msgstr ""

#: pypilot/rudder.py:194
msgid "servo rudder autogain failed"
msgstr ""

#: pypilot/sensors.py:43
msgid "sensor found"
msgstr ""

#: pypilot/sensors.py:192
msgid "unknown data parsed!"
msgstr ""

#: pypilot/serialprobe.py:31
msgid "error reading"
msgstr ""

#: pypilot/serialprobe.py:87
msgid "found more devices by path"
msgstr ""

#: pypilot/serialprobe.py:119
msgid "removing gps device"
msgstr ""

#: pypilot/serialprobe.py:195
msgid "no pyudev module! will scan usb devices often!"
msgstr ""

#: pypilot/serialprobe.py:357
msgid "success"
msgstr ""

#: pypilot/serialprobe.py:365
msgid "failed to record device"
msgstr ""

#: pypilot/server.py:97
msgid "ERROR no connections in watch"
msgstr ""

#: pypilot/server.py:200
msgid "remove duplicate udp connection"
msgstr ""

#: pypilot/server.py:340 ui/boatplot.py:110
msgid "failed to load"
msgstr ""

#: pypilot/server.py:351
msgid "backup data failed as well"
msgstr ""

#: pypilot/server.py:379
msgid "failed to write"
msgstr ""

#: pypilot/server.py:436
msgid "pypilot_server: bind failed; already running a server?"
msgstr ""

#: pypilot/server.py:498
msgid "persistent store took too long!"
msgstr ""

#: pypilot/server.py:514
msgid "max connections reached"
msgstr ""

#: pypilot/server.py:517
msgid "server add socket"
msgstr ""

#: pypilot/server.py:527
msgid "internal pipe closed, server exiting"
msgstr ""

#: pypilot/server.py:579
msgid "server socket closed from flush!!"
msgstr ""

#: pypilot/servo.py:449
msgid "servo calibration invalid"
msgstr ""

#: pypilot/servo.py:557
msgid "failed to open servo on:"
msgstr ""

#: pypilot/servo.py:564
msgid "failed set nonblocking/exclusive"
msgstr ""

#: pypilot/servo.py:595
msgid "found"
msgstr ""

#: pypilot/servo.py:716
msgid "loading servo calibration"
msgstr ""

#: pypilot/servo.py:720
msgid "WARNING: using default servo calibration!!"
msgstr ""

#: pypilot/servo.py:729
msgid "probing"
msgstr ""

#: pypilot/servo.py:745
msgid "arduino servo detected"
msgstr ""

#: pypilot/servo.py:754
msgid "device needed for option"
msgstr ""

#: pypilot/signalk.py:67
msgid "read token"
msgstr ""

#: pypilot/signalk.py:70
msgid "failed to read token"
msgstr ""

#: pypilot/signalk.py:77
msgid "failed to"
msgstr ""

#: pypilot/signalk.py:77
msgid "autodetection not possible"
msgstr ""

#: pypilot/signalk.py:78 pypilot/signalk.py:144 pypilot/signalk.py:213
msgid "try"
msgstr ""

#: pypilot/signalk.py:78 pypilot/signalk.py:144 pypilot/signalk.py:213
msgid "or"
msgstr ""

#: pypilot/signalk.py:109
msgid "service removed"
msgstr ""

#: pypilot/signalk.py:113
msgid "signalk server lost"
msgstr ""

#: pypilot/signalk.py:116
msgid "service add"
msgstr ""

#: pypilot/signalk.py:130
msgid "server found"
msgstr ""

#: pypilot/signalk.py:139
msgid "probe"
msgstr ""

#: pypilot/signalk.py:143
msgid "could not"
msgstr ""

#: pypilot/signalk.py:153
msgid "failed to retrieve/parse data from"
msgstr ""

#: pypilot/signalk.py:156
msgid "signalk found"
msgstr ""

#: pypilot/signalk.py:168
msgid "see if token is ready"
msgstr ""

#: pypilot/signalk.py:174
msgid "received token"
msgstr ""

#: pypilot/signalk.py:180
msgid "failed to store token"
msgstr ""

#: pypilot/signalk.py:184
msgid "error requesting access"
msgstr ""

#: pypilot/signalk.py:203
msgid "signalk request access url"
msgstr ""

#: pypilot/signalk.py:205
msgid "signalk error requesting access"
msgstr ""

#: pypilot/signalk.py:212
msgid "cannot create connection:"
msgstr ""

#: pypilot/signalk.py:226
msgid "failed to connect"
msgstr ""

#: pypilot/signalk.py:270
msgid "signalk connected to"
msgstr ""

#: pypilot/signalk.py:313
msgid "signalk failed to parse"
msgstr ""

#: pypilot/signalk.py:331
msgid "Exception converting signalk->pypilot"
msgstr ""

#: pypilot/signalk.py:345
msgid "received"
msgstr ""

#: pypilot/signalk.py:391
msgid "signalk failed to send"
msgstr ""

#: pypilot/signalk.py:404
msgid "signalk failed to parse msg:"
msgstr ""

#: pypilot/values.py:131
msgid "invalid initial value for range property"
msgstr ""

#: pypilot/values.py:180
msgid "invalid set"
msgstr ""

#: pypilot/pilots/__init__.py:25
msgid "ERROR loading"
msgstr ""

#: ui/autopilot_calibration.py:167
msgid "exception in calibration:"
msgstr ""

#: ui/autopilot_control.py:265
msgid "warning: unhandled message"
msgstr ""

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr ""

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr ""

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:455 ui/autopilot_control_ui.py:732
msgid "N/A"
msgstr ""

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr ""

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr ""

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr ""

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr ""

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr ""

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr ""

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:420
msgid "Compass"
msgstr ""

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr ""

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr ""

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr ""

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr ""

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr ""

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr ""

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr ""

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr ""

#: ui/autopilot_control_ui.py:299 ui/autopilot_control_ui.py:529
#: ui/autopilot_control_ui.py:649
msgid "Calibration"
msgstr ""

#: ui/autopilot_control_ui.py:349
msgid "Boat is level"
msgstr ""

#: ui/autopilot_control_ui.py:356 ui/client_wx.py:159 ui/scope_ui.py:94
msgid "Reset"
msgstr ""

#: ui/autopilot_control_ui.py:377
msgid "Alignment"
msgstr ""

#: ui/autopilot_control_ui.py:394
msgid "Heading"
msgstr ""

#: ui/autopilot_control_ui.py:399 ui/autopilot_control_ui.py:465
#: ui/autopilot_control_ui.py:475
msgid "     N/A     "
msgstr ""

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:755
msgid "Offset"
msgstr ""

#: ui/autopilot_control_ui.py:418
msgid "Coords"
msgstr ""

#: ui/autopilot_control_ui.py:420
msgid "Sea"
msgstr ""

#: ui/autopilot_control_ui.py:420
msgid "Boat"
msgstr ""

#: ui/autopilot_control_ui.py:443 ui/client_wx.py:52
msgid "Scope"
msgstr ""

#: ui/autopilot_control_ui.py:450
msgid "Pitch"
msgstr ""

#: ui/autopilot_control_ui.py:460
msgid "Roll"
msgstr ""

#: ui/autopilot_control_ui.py:470
msgid "Heel"
msgstr ""

#: ui/autopilot_control_ui.py:497
msgid "alignment"
msgstr ""

#: ui/autopilot_control_ui.py:539 ui/autopilot_control_ui.py:659
msgid "Calibration Age"
msgstr ""

#: ui/autopilot_control_ui.py:556 ui/autopilot_control_ui.py:676
msgid "Clear"
msgstr ""

#: ui/autopilot_control_ui.py:559 ui/autopilot_control_ui.py:679
msgid "calibration locked"
msgstr ""

#: ui/autopilot_control_ui.py:582
msgid "accel"
msgstr ""

#: ui/autopilot_control_ui.py:613
msgid "Sigma Points"
msgstr ""

#: ui/autopilot_control_ui.py:620
msgid "local history"
msgstr ""

#: ui/autopilot_control_ui.py:627
msgid "current"
msgstr ""

#: ui/autopilot_control_ui.py:634
msgid "Calibration Points"
msgstr ""

#: ui/autopilot_control_ui.py:703
msgid "compass"
msgstr ""

#: ui/autopilot_control_ui.py:713
msgid "Press each button when the rudder is at the correct position to calibrate."
msgstr ""

#: ui/autopilot_control_ui.py:727
msgid "Rudder"
msgstr ""

#: ui/autopilot_control_ui.py:742
msgid "Reset Calibration"
msgstr ""

#: ui/autopilot_control_ui.py:752
msgid "Rudder Is Centered"
msgstr ""

#: ui/autopilot_control_ui.py:760 ui/autopilot_control_ui.py:773
#: ui/autopilot_control_ui.py:786
msgid "------"
msgstr ""

#: ui/autopilot_control_ui.py:765
msgid "Rudder is Starboard Range"
msgstr ""

#: ui/autopilot_control_ui.py:768
msgid "Scale"
msgstr ""

#: ui/autopilot_control_ui.py:778
msgid "Rudder is Port Range"
msgstr ""

#: ui/autopilot_control_ui.py:781
msgid "Non Linearity"
msgstr ""

#: ui/autopilot_control_ui.py:798
msgid " range +-"
msgstr ""

#: ui/autopilot_control_ui.py:806
msgid "degrees"
msgstr ""

#: ui/autopilot_control_ui.py:825
msgid "rudder"
msgstr ""

#: ui/autopilot_control_ui.py:827
msgid "settings"
msgstr ""

#: ui/boatplot.py:26
msgid "failed to load pywavefront:"
msgstr ""

#: ui/boatplot.py:56
msgid "invalid display dimensions"
msgstr ""

#: ui/boatplot.py:111
msgid "Did you add the pypilot_data repository?"
msgstr ""

#: ui/boatplot.py:161
msgid "not found, texture compass cannot be used"
msgstr ""

#: ui/client_wx.py:48
msgid "Refresh"
msgstr ""

#: ui/client_wx.py:190
msgid "Connected"
msgstr ""

#: ui/client_wx.py:192
msgid "Disconnected"
msgstr ""

#: ui/client_wx.py:219
msgid "warning, invalid choice value specified"
msgstr ""

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr ""

#: ui/scope_ui.py:73
msgid "Zero"
msgstr ""

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr ""

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr ""

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr ""

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr ""

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr ""

#: ui/scope_ui.py:97
msgid "fftw"
msgstr ""

#: ui/scope_ui.py:100
msgid "Time"
msgstr ""

#: ui/scope_wx.py:68
msgid "values not found:"
msgstr ""

